-- Road Accidents Database Setup
-- Run these in Snowflake to recreate the schema

CREATE DATABASE IF NOT EXISTS ROAD_ACCIDENTS_DB;
CREATE SCHEMA IF NOT EXISTS ROAD_ACCIDENTS_DB.ANALYTICS;

CREATE OR REPLACE TABLE ROAD_ACCIDENTS_DB.ANALYTICS.ACCIDENTS (
    ACCIDENT_ID VARCHAR(20),
    DATE DATE,
    TIME VARCHAR(5),
    DAY_OF_WEEK VARCHAR(10),
    REGION VARCHAR(50),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    SEVERITY VARCHAR(10),
    NUM_VEHICLES INT,
    NUM_CASUALTIES INT,
    NUM_FATALITIES INT,
    NUM_INJURIES INT,
    ROAD_TYPE VARCHAR(30),
    SPEED_LIMIT INT,
    WEATHER VARCHAR(20),
    LIGHT_CONDITIONS VARCHAR(20),
    ROAD_SURFACE VARCHAR(15),
    VEHICLE_TYPE VARCHAR(20)
);

CREATE OR REPLACE FILE FORMAT ROAD_ACCIDENTS_DB.ANALYTICS.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    DATE_FORMAT = 'YYYY-MM-DD';

CREATE OR REPLACE STAGE ROAD_ACCIDENTS_DB.ANALYTICS.ACCIDENT_STAGE
    FILE_FORMAT = ROAD_ACCIDENTS_DB.ANALYTICS.CSV_FORMAT;
